[CTM]
location_data = "../datasets/enron/enron-train.txt"

EM_MAX_ITER = 50
EM_CONVERGED = 1e-6
INF_MAX_ITER = 100
LAMBDA = 100.0
threads = 4
n_topics = 50
p = 0.1
output_dir = "../models/enron/timerun1"
